version: "3.8"

services:
  mysql:
    build: ./mysql
    expose:
      - 3306

  redis:
    image: "redis:6.0.1"
    expose:
      - 6379

  server:
    build: ./server
    ports:
      - 8080:8080

  redisflush:
    build: ./redisToMysqlService